name: App Portfolio

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT: ${{ secrets.PROJECT_ID }}

permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          deliverables: app.yaml
          promote: true
          working_directory: './'
